### ISSUE TITLE
checkTypeForGoogle : 유저가 나가는 상황 방지

### ISSUE THREAD

**Issue by BulTTaeng** [BulTTaeng/NURU#23]
check_type_for_google 에서 유저가 구글 auth에만 등록을 하고 , 뒤에 나가버리는 경우 , firebase에 정보가 들어가지 않아서 문제가 생김

LoginFragment에서 auth에 등록도 하지 말고, 나중에 한번에 하는 방향으로 추진해야 함.

**Comment by kdjun97** [comment]
commit history : 1fd1f96047054123eee6d0c056a331fafc3fd2bf
